services:
  mysql-db:
    image: mysql:8.0.40-debian
    restart: unless-stopped
    # env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=itjob
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"

  app:
    depends_on:
      - mysql-db
    build:
      dockerfile: Dockerfile
    restart: on-failure
    # env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/itjob
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - HDL_UPLOAD-DIR_BASE-URI-PATH=file:///uploads/
    volumes:
      - ../upload-docker/:/uploads/
    stdin_open: true
    tty: true

volumes:
  db:

    # docker compose up -d
